"""Shared helpers for the torch effective-congruence battery (spec 08 §8).

The battery's tests assert; this module carries the plumbing they share — oracle/torch AAT
conversion, weight readback, and the report sink. Every test records what it measured via
``record``; the conftest session hook writes ``tests/congruence_report.md`` so the run leaves
a reviewable artifact regardless of pass/fail. Alex signs off on the report; the tests only
have to run and report.
"""

import collections
import datetime
import pathlib

import numpy as np

REPORT_PATH = pathlib.Path(__file__).parent / "congruence_report.md"
_entries = collections.defaultdict(list)          # (module, tier) -> [line, ...]


def record(module, tier, line):
    """Add one finding to the congruence report, e.g. record("Classifier", 1, "...")."""
    _entries[(module, tier)].append(line)


def write_report():
    if not _entries:
        return
    lines = ["# Effective-congruence report — torch L1 modules",
             f"\nGenerated by the test battery, {datetime.datetime.now():%Y-%m-%d %H:%M}. "
             "Tiers per spec 08 §8: 1 = bit-exact anchor, 2 = noise law, "
             "3 = learning outcomes, 4 = generation behavior.\n"]
    for (module, tier) in sorted(_entries):
        lines.append(f"\n## {module} — tier {tier}\n")
        for entry in _entries[(module, tier)]:
            lines.append(f"- {entry}")
    REPORT_PATH.write_text("\n".join(lines) + "\n")


def to_oracle_aat(aat_row):
    """torch/int row -> the oracle's list AAT (-1 becomes None)."""
    return [None if int(a) < 0 else int(a) for a in aat_row]


def oracle_weights(core):
    """(Ga, Gb) int arrays [lanes, spaces, channels] read off a live oracle Core."""
    L = core.num_lanes
    K = core.spaces_per_lane
    S = core.crossbar_rows * core.crossbar_cols
    ga = np.empty((L, K, S), dtype=np.int64)
    gb = np.empty((L, K, S), dtype=np.int64)
    for lane_i in range(L):
        lane = core.lane(lane_i)
        for k, space in enumerate(lane.spaces):
            ga[lane_i, k] = [int(space.a.device_at(s).g()) for s in range(S)]
            gb[lane_i, k] = [int(space.b.device_at(s).g()) for s in range(S)]
    return ga, gb


def oracle_rank_cut_padded(tup, width):
    """The oracle's variable-length rank-cut tuple, -1-padded to the torch fixed width."""
    out = np.full(width, -1, dtype=np.int64)
    out[:len(tup)] = tup
    return out
